name: Self Heal Your Code
description: Use Magic
inputs:
  current_job_id:
    description: "job id"
    required: true

  token:
    description: "github token"
    required: true
      
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get error logs
      shell: bash
      run: gh run view --job ${{ inputs.current_job_id }} --log > error.log; cat error.log >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.token }}


