name: Build
on:
  workflow_dispatch:
  pull_request:

env:
  IMAGE: ghcr.io/msp5382/demo-self-healing-code/pr:main

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Call GPT for help
        if: failure()
        run: gh run view --job ${{ github.job }} --log | grep error > error.log \
             cat error.log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
