name: Self Heal Your Code
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      current_job_id:
        required: true
        type: number
      
jobs:
    summon-chatgpt:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Get error logs
              run: gh run view --job ${{ steps.get-job-id.outputs.job_id }} --log > error.log; cat error.log
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14 # Choose the desired Node.js version

